name: autograding-codespace-python
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - ipykernel
  - pytest
  - pip:
     - -e .  # install git checkout of package in editable mode
