# Base image
FROM continuumio/miniconda3

# Set the ARG for the Python version
ARG PYTHON_VERSION="3.10"

# Create a Python environment using Mamba
RUN conda install -c conda-forge mamba \
   && mamba create -n venv python=$PYTHON_VERSION

# Activate the environment
SHELL ["conda", "run", "-n", "my_miniconda_env", "/bin/bash", "-c"]

# Copy the requirements file
COPY requirements.txt /tmp/

# Install the requirements using Mamba
RUN mamba install --file /tmp/requirements.txt

# Clean up
RUN rm -rf /tmp/requirements.txt